apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: zipkin
spec:
  selector:
    matchLabels:
      service: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: zipkin
    spec:
      containers:
      - image: openzipkin/zipkin
        name: zipkin
        ports:
        - containerPort: 9411
        - containerPort: 9410
      restartPolicy: Always
