
server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - argocd.tcc
    paths:
      - /
    pathType: Prefix
    extraPaths:
      []
    https: false
  extraArgs:
    - --insecure
