{{ if .Values.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipkin
  annotations:
      kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.serviceName }}
            port:
              number: {{ .Values.service.servicePort }}
{{ end }}
